keybinds:
  - name: tileLeft
    mapping: <Super>Left
    action: tile
    xpos: 0
    ypos: 0
    height: 100
    width: 50
  - name: tileRight
    mapping: <Super>Right
    action: tile
    xpos: 50
    ypos: 0
    height: 100
    width: 50
  - name: tileTop
    mapping: <Super>Up
    action: tile
    xpos: 0
    ypos: 0
    height: 50
    width: 100
  - name: tileBottom
    mapping: <Super>Down
    action: tile
    xpos: 0
    ypos: 50
    height: 50
    width: 100
  - name: tileTopLeft
    mapping: <Ctrl>Up+Left
    action: tile
    xpos: 0
    ypos: 0
    height: 50
    width: 50